// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class PetSearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "C:\\drivers\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void petSearch() {
    // Test name: PetSearch
    // Step # | name | target | value
    // 1 | open | /actions/Catalog.action | 
    driver.get("https://petstore.octoperf.com/actions/Catalog.action");
    // 2 | setWindowSize | 1380x601 | 
    driver.manage().window().setSize(new Dimension(1380, 601));
    // 3 | click | xpath=//*[@id='QuickLinks']/a[2]/img | 
    driver.findElement(By.xpath("//*[@id=\'QuickLinks\']/a[2]/img")).click();
    // 4 | click | linkText=K9-BD-01 | 
    driver.findElement(By.linkText("K9-BD-01")).click();
    // 5 | click | linkText=EST-6 | 
    driver.findElement(By.linkText("EST-6")).click();
    // 6 | click | linkText=Add to Cart | 
    driver.findElement(By.linkText("Add to Cart")).click();
    // 7 | click | xpath=//input[@name='EST-6'] | 
    driver.findElement(By.xpath("//input[@name=\'EST-6\']")).click();
    // 8 | type | name=EST-6 | 10
    WebElement quantity = driver.findElement(By.name("EST-6"));
    quantity.clear();
    quantity.sendKeys("10");
    // 9 | click | name=updateCartQuantities | 
    driver.findElement(By.name("updateCartQuantities")).click();
    // 10 | assertText | xpath=//*[@id="Cart"]/form/table/tbody/tr[2]/td[7] | $185.00
    assertThat(driver.findElement(By.xpath("//*[@id=\"Cart\"]/form/table/tbody/tr[2]/td[7]")).getText(), is("$185.00"));
  }
}
